
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 30 11:04:31 GMT 2015
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LSQBRACKET = 4;
  public static final int LBRACE = 6;
  public static final int COLON = 3;
  public static final int NUMBER = 8;
  public static final int BOOLEAN = 10;
  public static final int NULL = 11;
  public static final int RSQBRACKET = 5;
  public static final int STRING = 9;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMMA = 2;
  public static final int RBRACE = 7;
}

